### ISSUE TITLE
部署到服务器要怎么开启开机启动

### ISSUE THREAD

**Issue by ouyang-yuxuan** [quincyyhuang/hexo-node-admin#10]
部署到服务器要怎么开启开机启动，本地的Windows系统要怎么开机启动呢

hexo-server.vbs
-------------------------
set ws=WScript.CreateObject("WScript.Shell")
ws.Run "E:\\Blog\\farthest\\hexo-server.bat /start",0

--------------------------

hexo-server.bat
-------------------------------
E:
cd E:\Blog\farthest
hexo s -d

cd E:\Blog\farthest\hexo-node-admin
npm start
-------------------------------

这是我本地的自动启动，hexo s可以开机启动，npm start就不行了

还有就是服务器怎么开机启动呢？
谢谢指点

**Comment by quincyyhuang** [comment]
你好，部署到服务器，一般会使用进程守护程序。nodejs程序最常用的进程守护程序就是`pm2`，http://pm2.keymetrics.io/ 可以参考使用pm2作为进程守护的工具。另外，pm2也提供了一些在windows系统上的启动脚本 http://pm2.keymetrics.io/docs/usage/startup/#windows-consideration 希望可以帮到你。

**Comment by ouyang-yuxuan** [comment]
。。。英语不好，看不懂

**Comment by quincyyhuang** [comment]
closed due to not relevant
