### ISSUE TITLE
用custom的部署方式，点部署后就一直在部署中

### ISSUE THREAD

**Issue by welkinbai** [quincyyhuang/hexo-node-admin#11]
如题，我博客实际上部署在服务器上，文章新增后不需要部署到第三方的page。但是我需要用git对文章的md文件做个备份。
所以我自己写了部署脚本，希望点击部署后就git push到远程仓库去。
脚本如下：
```
#!/bin/bash
cd /root/dawnBlog/
git add --all
git commit -m "commit"
git push
echo "Deploy done"
exit 0
```
现在当点击部署的时候，会一直有个部署中的东西。但是实际上这个脚本已经执行完毕了，远程仓库已经更新了。不知道哪里有问题，感觉脚本执行结束了程序并没有检测到。

**Comment by quincyyhuang** [comment]
感谢反馈！我抽空找一下bug，有更新会及时回复

**Comment by quincyyhuang** [comment]
问题在v0.1.5中得到解决，感谢你的反馈！
