### ISSUE TITLE
文章编辑器的文字背景为什么是红色的

### ISSUE THREAD

**Issue by welkinbai** [quincyyhuang/hexo-node-admin#13]
如下图，这红仆仆的一片，看着难受，能换嘛？
![image](https://user-images.githubusercontent.com/13196370/44299396-6ea29180-a327-11e8-87ff-0b60bf7d3586.png)

**Comment by quincyyhuang** [comment]
你好，感谢你的反馈！我这里无法复现你说的问题，请问你用的是什么浏览器？

**Comment by quincyyhuang** [comment]
你好！我在simplemde的issue中找到了问题，红色的出现是因为它默认开启了spell check，后续我将加入用户对编辑器的设置，非常感谢！

目前你只能手动修改 `views/editor.pug` 中的如下片段
![image](https://user-images.githubusercontent.com/10793921/44300610-83d5eb00-a33c-11e8-83d3-6edf7979c377.png)
在simplemde的设置中添加 `spellChecker: false` 来关闭拼写检查

reference: https://github.com/sparksuite/simplemde-markdown-editor/issues/441
