### ISSUE TITLE
npm start 显示Bad config file.不能启动

### ISSUE THREAD

**Issue by ouyang-yuxuan** [quincyyhuang/hexo-node-admin#4]
npm start 显示Bad config file.不能启动

**Comment by quincyyhuang** [comment]
你好，可以把你的 config.json 文件贴出来吗？

**Comment by ouyang-yuxuan** [comment]
{
    "port": 4001,
    "hexo_dir": "",
    "admin": {
        "username": "test",
        "password": "test",
        "plain": true
    },
    "deploy": {
        "type": "default",
        "script": ""
    },
    "lang": "zh_CN"
}

**Comment by ouyang-yuxuan** [comment]
这个可以脱离hexo s运行吗

**Comment by ouyang-yuxuan** [comment]
![image](https://user-images.githubusercontent.com/36830421/37863924-a644119e-2fa1-11e8-9ec1-9c6a87a7d591.png)

**Comment by quincyyhuang** [comment]
你好，问题应该在于：如果`hexo_dir`留空的话，默认的运行目录是hexo-node-admin，而在此处正确的`hexo_dir`应该是`E:/Blog/farthest`或者`E:\\Blog\\farthest`。

非常感谢你的反馈！可能将留空的默认目录改为上一级目录从逻辑上和使用上会更合理一些，我会再考虑一下看是否作出修改，感谢！

**Comment by quincyyhuang** [comment]
另外，可以脱离hexo server运行，本后台是独立于hexo的server的。

**Comment by ouyang-yuxuan** [comment]
那意思是完全不用运行hexo 直接可以进行文档编写，可以部署上服务器作为在线编辑吗？可以一直运行在服务器上面吗

**Comment by quincyyhuang** [comment]
对的，可以一直部署在服务器上，我就是这样用的。但是服务器上必须也要装hexo，因为后台其实还是要执行hexo generate, hexo deploy, hexo clean等命令。
![qq 20180325120953](https://user-images.githubusercontent.com/10793921/37871643-72c7f04a-3025-11e8-8f46-b5fcb03cef93.png)
