### ISSUE TITLE
部署错误

### ISSUE THREAD

**Issue by ouyang-yuxuan** [quincyyhuang/hexo-node-admin#5]
![image](https://user-images.githubusercontent.com/36830421/37870331-0fe33c06-3006-11e8-944e-4df7a52ea670.png)

**Comment by quincyyhuang** [comment]
请发一下`config.json`和部署脚本的内容谢谢！

**Comment by ouyang-yuxuan** [comment]
难道需要自己配置部署脚本的吗

**Comment by ouyang-yuxuan** [comment]
{
    "port": 4001,
    "admin": {
        "username": "test",
        "password": "test",
        "plain": true
    },
    "hexo_dir": "E:/Blog/farthest",
    "deploy": {
        "type": "default",
        "script": ""
    },
    "lang": "zh_CN"
}

**Comment by ouyang-yuxuan** [comment]
自己要写hexo c g d的吗？

**Comment by quincyyhuang** [comment]
如果设置成default，后台其实只执行了hexo deploy命令，真正的部署是你在`_config.yml`，也就是hexo自己的部署办法中设置的，出现的问题就是hexo deploy的问题，请检查一下本身hexo deploy命令能否顺利执行:D

**Comment by quincyyhuang** [comment]
简单来说，后台支持两种部署方式。
1. default，后台直接执行`hexo deploy`，调用hexo的部署。
2. custom，后台执行在`config.json`中设定的部署脚本，进行自定义行为的部署。

希望可以帮到你:D

**Comment by ouyang-yuxuan** [comment]
本地的hexo deploy是可以执行的

**Comment by quincyyhuang** [comment]
已确认是一个bug，因为我自己是用的自定义部署脚本，可能没发现default的问题，正在修改，谢谢反馈！

**Comment by quincyyhuang** [comment]
Fixed!
