### ISSUE TITLE
点击保存按钮不能上传到服务器（部署到coding或者github）中

### ISSUE THREAD

**Issue by ouyang-yuxuan** [quincyyhuang/hexo-node-admin#7]
![image](https://user-images.githubusercontent.com/36830421/37872627-32f66a28-303e-11e8-81b3-4ff8319034bd.png)

**Comment by quincyyhuang** [comment]
因为hexo写文章的workflow是编辑markdown，然后generate生成静态文件，然后deploy将静态文件部署到服务器或空间，这里的保存其实就是保存到markdown的意思，如果要更新静态文件还是请再generate和deploy xD

**Comment by ouyang-yuxuan** [comment]
这个意思容易误解，我觉得把这个按钮添用来执行generate和deploy
不过这个想法也还不错呀，这样就不用专门去下面选项中去点击生成和部署按钮了


---------------------------------------------
现在部署用不了是吧，也就是还是不能生成部署到代码托管那里吧

**Comment by quincyyhuang** [comment]
hhh这个保存我就不改啦，可以加一点说明上去，改了感觉对hexo博客本身的操作流程就有点invasive了，有的时候可能只是想修改或者先保存修改，并不一定写好了就会发布，部署我已经改好了，测试没有问题了就发新版：D

**Comment by ouyang-yuxuan** [comment]
好的，非常感谢
